# Generated by Django 4.1.7 on 2023-03-29 13:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("090120ac-4878-4e8f-8ae8-7e714d35a384"),
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("duration", models.PositiveIntegerField()),
                ("maxGroupSize", models.PositiveIntegerField()),
                ("difficulty", models.CharField(max_length=50)),
                ("ratingQuantity", models.IntegerField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("summary", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1024, null=True),
                ),
                (
                    "imgCover",
                    models.ImageField(blank=True, null=True, upload_to="nft/images"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="NftImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nft_image",
                    models.ImageField(blank=True, null=True, upload_to="nft/nft_"),
                ),
                (
                    "nft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nft_images",
                        to="nft_api.nft",
                    ),
                ),
            ],
        ),
    ]
