# Generated by Django 4.1.7 on 2023-03-29 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("nft_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nft",
            name="ratingAverage",
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="nft",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b7830e13-87a4-4e44-b604-41be3fd9f3ff"),
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
