# Generated by Django 4.1.7 on 2023-03-29 14:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("nft_api", "0002_nft_ratingaverage_alter_nft_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nft",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
